config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'payment_method_categories#index'

  resources :payment_method_categories
  resources :payment_method_institutions
  resources :payment_methods

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
	belongs_to :billing_account
	has_many :bill_payments
end

app/models/bill_payment.rb
class BillPayment < ApplicationRecord
	belongs_to :bill
	has_one :payment_method
	has_one :payment_method_category, through: :payment_method
	has_one :payment_method_institution, through: :payment_method
end

app/models/billing_account.rb
class BillingAccount < ApplicationRecord
	has_many :bills
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
	belongs_to :payment_method_institution
	belongs_to :payment_method_category
	has_many :bill_payments
end

app/models/payment_method_category.rb
class PaymentMethodCategory < ApplicationRecord
	has_many :payment_methods
	has_many :payment_method_institutions, through: :payment_methods
	has_many :bill_payments, through: :payment_methods
end

app/models/payment_method_institution.rb
class PaymentMethodInstitution < ApplicationRecord
	has_many :payment_methods
	has_many :payment_method_categories, through: :payment_methods
	has_many :bill_payments, through: :payment_methods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/payment_method_categories_controller.rb
class PaymentMethodCategoriesController < ApplicationController

    before_action :set_payment_method_category, only: [:edit, :show, :update, :destroy]

    def index
        @payment_method_categories = PaymentMethodCategory.all
    end

    def new
        @payment_method_category = PaymentMethodCategory.new
    end

    def create
        if PaymentMethodCategory.create(payment_method_category_params)
            # flash[:success] = "Payment Method Category Added"
            redirect_to root_path
        else
            render :new
        end
    end

    def update
        payment_method_category = PaymentMethodCategory.find(params[:id])
        if payment_method_category.update(payment_method_category_params)
            redirect_to root_path
        else
            render :edit
        end
    end

    def destroy
        if PaymentMethodCategory.destroy(params.require(:id))
            redirect_to root_path
        else
            render :index
        end
    end

    private

    def set_payment_method_category
        @payment_method_category = PaymentMethodCategory.find(params[:id])
    end

    def payment_method_category_params
        params.require(:payment_method_category).permit(:name)
    end

end

app/controllers/payment_method_institutions_controller.rb
class PaymentMethodInstitutionsController < ApplicationController

    before_action :set_payment_method_institution, only: [:edit, :show, :update, :destroy]

    def index
        @payment_method_institutions = PaymentMethodInstitution.all
    end

    def new
        @payment_method_institution = PaymentMethodInstitution.new
    end

    def create
        if PaymentMethodInstitution.create(payment_method_institution_params)
            # flash[:success] = "Payment Method Institution Added"
            redirect_to root_path
        else
            render :new
        end
    end

    def update
        payment_method_institution = PaymentMethodInstitution.find(params[:id])
        if payment_method_institution.update(payment_method_institution_params)
            redirect_to root_path
        else
            render :edit
        end
    end

    def destroy
        if PaymentMethodInstitution.destroy(params.require(:id))
            redirect_to root_path
        else
            render :index
        end
    end

    private

    def set_payment_method_institution
        @payment_method_institution = PaymentMethodInstitution.find(params[:id])
    end

    def payment_method_institution_params
        params.require(:payment_method_institution).permit(:name)
    end

end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController

    before_action :set_payment_method, only: [:edit, :show, :update, :destroy]

    def index
        @payment_methods = PaymentMethod.all
    end

    def new
        @payment_method = PaymentMethod.new
    end

    def create
        if PaymentMethod.create!(payment_method_params)
            redirect_to payment_methods_path
        else
            render :new
        end
    end

    def update
        payment_method = PaymentMethod.find(params[:id])
        if payment_method.update!(payment_method_params)
            redirect_to payment_methods_path
        else
            render :edit
        end
    end

    def destroy
        if PaymentMethod.destroy(params.require(:id))
            redirect_to payment_methods_path
        else
            render :index
        end
    end

    private

    def set_payment_method
        @payment_method = PaymentMethod.find(params[:id])
    end

    def payment_method_params
        params.require(:payment_method).permit(:name, :payment_method_category_id, :payment_method_institution_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<%= link_to 'Payment Method Categories', payment_method_categories_path %>
|
<%= link_to 'Payment Method Institutions', payment_method_institutions_path %>
|
<%= link_to 'Payment Methods', payment_methods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceGrinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/payment_method_categories/_form.html.erb
<%= form_for @payment_method_category do |f| %>
    <%= f.hidden_field :id %>

    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>

    <br/><br/>

    <%= f.submit 'Save Payment Method Category' %>

<% end %>

app/views/payment_method_categories/edit.html.erb
<h1>Edit Payment Method Category</h1>

<%= render 'form', url: payment_method_categories_url, method: :patch %>

app/views/payment_method_categories/index.html.erb
<h1>Payment Method Categories</h1>
<table>
    <thead>
        <tr>
            <th scope="col">&nbsp;</th>
            <th scope="col">Name</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @payment_method_categories.each_with_index do |payment_method_category, index| %>
            <tr>
                <td><%= index+1 %>.</td>
                <td><%= link_to payment_method_category.name, payment_method_categories_path(payment_method_category) %></td>
                <td>
                    <%= link_to 'Edit', edit_payment_method_category_url(payment_method_category) %>
                    <%= link_to 'Delete', payment_method_category_url(payment_method_category), method: :delete, data: {confirm: "Are you sure?"} %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Add Payment Method Category', new_payment_method_category_path %>

app/views/payment_method_categories/new.html.erb
<h1>Add Payment Method Category</h1>

<%= render 'form', url: payment_method_categories_url, method: :post %>

app/views/payment_method_institutions/_form.html.erb
<%= form_for @payment_method_institution do |f| %>
    <%= f.hidden_field :id %>

    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>

    <br/><br/>

    <%= f.submit 'Save Payment Method Institution' %>

<% end %>

app/views/payment_method_institutions/edit.html.erb
<h1>Edit Payment Method Category</h1>

<%= render 'form', url: payment_method_institutions_url, method: :patch %>

app/views/payment_method_institutions/index.html.erb
<h1>Payment Method Institutions</h1>
<table>
<thead>
        <tr>
            <th scope="col">&nbsp;</th>
            <th scope="col">Name</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @payment_method_institutions.each_with_index do |payment_method_institution, index| %>
            <tr>
                <td><%= index+1 %>.</td>
                <td><%= link_to payment_method_institution.name, payment_method_institutions_path(payment_method_institution) %></td>
                <td>
                    <%= link_to 'Edit', edit_payment_method_institution_url(payment_method_institution) %>
                    <%= link_to 'Delete', payment_method_institution_url(payment_method_institution), method: :delete, data: {confirm: "Are you sure?"} %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Add Payment Method Institution', new_payment_method_institution_path %>

app/views/payment_method_institutions/new.html.erb
<h1>Add Payment Method Institution</h1>

<%= render 'form', url: payment_method_institutions_url, method: :post %>

app/views/payment_methods/_form.html.erb
<%= form_for @payment_method do |f| %>
    <%= f.hidden_field :id %>

    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>

    <br/><br/>

    <%= f.label :payment_method_category_id, 'Category' %>
    <%= f.collection_select :payment_method_category_id, PaymentMethodCategory.all, :id, :name, include_blank: '- SELECT -' %>

    <br/><br/>

    <%= f.label :payment_method_institution_id, 'Institution' %>
    <%= f.collection_select :payment_method_institution_id, PaymentMethodInstitution.all, :id, :name, include_blank: '- SELECT -' %>

    <br/><br/>

    <%= f.submit 'Save Payment Method' %>

<% end %>

app/views/payment_methods/edit.html.erb
<h1>Edit Payment Method</h1>

<%= render 'form', url: payment_methods_url, method: :patch %>

app/views/payment_methods/index.html.erb
<h1>Payment Methods</h1>
<table>
    <thead>
        <tr>
            <th scope="col">&nbsp;</th>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Institution</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @payment_methods.each_with_index do |payment_method, index| %>
            <tr>
                <td><%= index+1 %>.</td>
                <td><%= link_to payment_method.name, payment_methods_path(payment_method) %></td>
                <td><%= payment_method.payment_method_category.name %></td>
                <td><%= payment_method.payment_method_institution.name %></td>
                <td>
                    <%= link_to 'Edit', edit_payment_method_url(payment_method) %>
                    <%= link_to 'Delete', payment_method_url(payment_method), method: :delete, data: {confirm: 'Are you sure?'} %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Add Payment Method', new_payment_method_path %>

app/views/payment_methods/new.html.erb
<h1>Add Payment Method</h1>

<%= render 'form', url: payment_methods_url, method: :post %>